### ISSUE TITLE
Locale issues installing from pip

### ISSUE THREAD

**Issue by jrjhealey** [Benjamin-Lee/CodonAdaptationIndex#4]
Hi Ben,

I just thought I’d let you know about an issue with installing I found. I’ve hacked my way around it, but others may encounter it.

Any variation of `pip3 install CAI` greeted me with:

```python
Processing /home/wms_joe/repos/CodonAdaptationIndex
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-441r21d4/setup.py", line 7, in <module>
        long_description = f.read()
      File "/home/wms_joe/bin/miniconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2445: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-441r21d4/
```

Searching online suggests its a locale encoding issue, however I tried to set several locale environmental variables, as corresponds to other issues I’ve seen for this ascii error:

```
export LC_ALL=C
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
```

None of which worked.

The issue appears to be with the `README.rst`, so I was able to finally install it inside a cloned repo with `pip3 install .` after emptying the contents of the file. I’m still not sure exactly where the issue arises though, as at a glance, I couldn’t see an unusual character anywhere.

### Edit:
Subsequently discovered that, contrary to the internet’s advice, the encoding should be `en_US.utf8` not `UTF-8`. Though I suspect that may be due to this being installed on an older ubuntu box (14.04!).

Fortunately, `click` outputs a useful error message, and setting `LC_ALL` to `en_US.utf8` allowed the program to run correctly (I haven’t checked if that is also the case for the installation as it’s already on the system now).

```
Traceback (most recent call last):
  File "/home/wms_joe/bin/miniconda3/bin/CAI", line 11, in <module>
    sys.exit(cli())
  File "/home/wms_joe/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/wms_joe/bin/miniconda3/lib/python3.6/site-packages/click/core.py", line 696, in main
    _verify_python3_env()
  File "/home/wms_joe/bin/miniconda3/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
    ' mitigation steps.' + extra
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales were
discovered: en_US.utf8
$ export LC_ALL=en_US.utf8
$ CAI -h
Usage: CAI [OPTIONS]
Try "CAI --help" for help.

Error: no such option: -h

```

I don’t know if you want to consider this resolved or if this is something worth patching/including in the install instructions?!

**Comment by wdecoster** [comment]
FWIW I fixed a very similar issue with

`long_description=open(path.join(here, "README.md"), encoding='utf-8').read(),`

**Comment by Benjamin-Lee** [comment]
Thanks @wdecoster for the tip!

I believe f64050a will fix this issue – let me know if it doesn't.
